function fn_list = GetSurveySEStructFields()
    fn_list = {'Subject', 'Date', 'Session', 'Set', 'Ch1','Ch2', 'Ch3',...
        'Ch4', 'ElectrodeID','StartTime', 'EndTime', 'Amp','Freq','PW',...
        'Dur','PRat','IPI','CatFirst','Base', 'Annotation', 'NumSense',...
        'Model','ModelName','PFQualities','PFBasics'};
end
