function fn_list = GetSurveyOLSStructFields()
    fn_list = {'Subject', 'Date', 'Session', 'Set', 'Block', 'Trial', 'Ch1',...
        'Ch2', 'Ch3', 'Ch4', 'NumSens', 'Quality', 'SkinDepth', 'Comments',...
        'SurveyType', 'PalmarBoundary', 'PalmarIdx', 'PalmarLoc',...
        'DorsumBoundary', 'DorsumIdx', 'DorsumLoc'};
end
